apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Shutver/taller-kubernetes-nextDigital.git
    targetRevision: HEAD
    path: practica/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: practica
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
